const $=id=>document.getElementById(id);
const DB_CUSTOMERS="drivetrack_customers_v1", DB_TRIPS="drivetrack_trips_v1";
let customers=load(DB_CUSTOMERS,[]), trips=load(DB_TRIPS,[]), tracking=false, watchId=null, currentTrip=null, lastPoint=null, distanceM=0, timer=null, currentPosition=null;
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function save(){localStorage.setItem(DB_CUSTOMERS,JSON.stringify(customers));localStorage.setItem(DB_TRIPS,JSON.stringify(trips))}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function km(m){return (m/1000).toFixed(2)+" km"}
function duration(ms){let s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=s%60;return [h,m,sec].map(x=>String(x).padStart(2,"0")).join(":")}
function switchTab(tab){document.querySelectorAll(".tab-panel").forEach(x=>x.classList.toggle("hidden",x.id!==tab));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));if(tab==="customers")renderCustomers();if(tab==="history")renderTrips()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
function renderCustomers(){let q=$("customerSearch").value.toLowerCase();let list=customers.filter(c=>[c.name,c.address,c.notes,c.phone].join(" ").toLowerCase().includes(q));$("customerList").innerHTML=list.length?list.map(c=>`<article class="customer-card"><h3>${esc(c.name)}</h3><p>📍 ${esc(c.address)}</p>${c.phone?`<p>☎ ${esc(c.phone)}</p>`:""}${c.notes?`<p>📝 ${esc(c.notes)}</p>`:""}<p class="muted small">${c.lat!=null&&c.lng!=null?`GPS: ${Number(c.lat).toFixed(5)}, ${Number(c.lng).toFixed(5)}`:"GPS coordinates not saved"}</p><div class="card-actions"><button class="secondary" onclick="editCustomer('${c.id}')">Edit</button><button class="secondary" onclick="navigateCustomer('${c.id}')">Map</button><button class="danger" onclick="deleteCustomer('${c.id}')">Delete</button></div></article>`).join(""):'<div class="empty">No customers yet. Tap Add to create your first record.</div>'}
$("customerSearch").addEventListener("input",renderCustomers);
function resetForm(){$("customerForm").reset();$("customerId").value="";$("formTitle").textContent="Add customer"}
$("newCustomerBtn").onclick=()=>{$("customerForm").classList.remove("hidden");resetForm();$("customerName").focus()};
$("cancelCustomer").onclick=()=>{$("customerForm").classList.add("hidden");resetForm()};
window.editCustomer=id=>{let c=customers.find(x=>x.id===id);if(!c)return;$("customerForm").classList.remove("hidden");$("formTitle").textContent="Edit customer";$("customerId").value=c.id;$("customerName").value=c.name;$("customerAddress").value=c.address;$("customerPhone").value=c.phone||"";$("customerNotes").value=c.notes||"";$("customerLat").value=c.lat??"";$("customerLng").value=c.lng??"";$("customerForm").scrollIntoView({behavior:"smooth",block:"start"})};
$("customerForm").onsubmit=e=>{e.preventDefault();let id=$("customerId").value;let c={id:id||crypto.randomUUID(),name:$("customerName").value.trim(),address:$("customerAddress").value.trim(),phone:$("customerPhone").value.trim(),notes:$("customerNotes").value.trim(),lat:$("customerLat").value===""?null:Number($("customerLat").value),lng:$("customerLng").value===""?null:Number($("customerLng").value)};if(id)customers=customers.map(x=>x.id===id?c:x);else customers.push(c);save();$("customerForm").classList.add("hidden");resetForm();renderCustomers()};
window.deleteCustomer=id=>{let c=customers.find(x=>x.id===id);if(c&&confirm(`Delete ${c.name}?`)){customers=customers.filter(x=>x.id!==id);save();renderCustomers()}};
window.navigateCustomer=id=>{let c=customers.find(x=>x.id===id);if(c){let url=c.lat!=null&&c.lng!=null?`https://www.google.com/maps/dir/?api=1&destination=${c.lat},${c.lng}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c.address)}`;window.open(url,"_blank")}};
function getPosition(success,failure){if(!navigator.geolocation){failure(new Error("This browser does not support GPS."));return}navigator.geolocation.getCurrentPosition(success,failure,{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
$("captureCustomerGps").onclick=()=>getPosition(p=>{$("customerLat").value=p.coords.latitude;$("customerLng").value=p.coords.longitude;alert("GPS coordinates added. Save the customer to keep them.")},e=>alert("Could not get GPS: "+e.message+". Check location permissions and use HTTPS."));
function nearestCustomer(pos){let best=null;for(const c of customers){if(c.lat==null||c.lng==null||!Number.isFinite(Number(c.lat))||!Number.isFinite(Number(c.lng)))continue;let d=meters(pos.latitude,pos.longitude,Number(c.lat),Number(c.lng));if(!best||d<best.distance)best={customer:c,distance:d}}return best}
function meters(a,b,c,d){const R=6371000,rad=x=>x*Math.PI/180,dp=rad(c-a),dl=rad(d-b),v=Math.sin(dp/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))}
function showPosition(pos){currentPosition=pos.coords;$("coords").textContent=`Latitude ${pos.coords.latitude.toFixed(6)} · Longitude ${pos.coords.longitude.toFixed(6)} · Accuracy ±${Math.round(pos.coords.accuracy)} m`;$("mapBtn").disabled=false;$("matchBtn").disabled=false;$("gpsStatus").textContent="GPS fix received";let match=nearestCustomer(pos.coords);$("nearest").textContent=match?`Nearest saved destination: ${match.customer.name} · ${Math.round(match.distance)} m away${match.distance<=100?" · Possible arrival":""}`:"No customer has GPS coordinates yet. Add coordinates to destination records.";if(tracking){let point={lat:pos.coords.latitude,lng:pos.coords.longitude,time:new Date().toISOString(),accuracy:pos.coords.accuracy};if(lastPoint){let d=meters(lastPoint.lat,lastPoint.lng,point.lat,point.lng);if(d<1000&&pos.coords.accuracy<100)distanceM+=d}lastPoint={lat:point.lat,lng:point.lng};currentTrip.points.push(point);if(match&&match.distance<=100&&(!currentTrip.stops.length||currentTrip.stops[currentTrip.stops.length-1].customerId!==match.customer.id)){let prev=currentTrip.stops[currentTrip.stops.length-1];if(!prev||Date.now()-new Date(prev.arrival).getTime()>120000)currentTrip.stops.push({customerId:match.customer.id,name:match.customer.name,address:match.customer.address,arrival:point.time,lat:point.lat,lng:point.lng})}updateTripUI()}}
$("startBtn").onclick=()=>{if(tracking)return;if(!navigator.geolocation){alert("GPS is not available in this browser.");return}tracking=true;distanceM=0;lastPoint=null;currentTrip={id:crypto.randomUUID(),start:new Date().toISOString(),end:null,distanceM:0,points:[],stops:[]};$("startBtn").disabled=true;$("stopBtn").disabled=false;$("tripStatus").textContent="Trip in progress";$("gpsStatus").textContent="Requesting GPS permission…";$("gpsDot").style.background="#d6f06b";getPosition(p=>{showPosition(p);watchId=navigator.geolocation.watchPosition(showPosition,e=>{$("gpsStatus").textContent="GPS issue: "+e.message},{enableHighAccuracy:true,maximumAge:5000,timeout:20000})},e=>{tracking=false;$("startBtn").disabled=false;$("stopBtn").disabled=true;$("tripStatus").textContent="Ready to drive";alert("GPS could not start: "+e.message+". Make sure DriveTrack is opened over HTTPS and location access is allowed.")});timer=setInterval(updateTripUI,1000)};
$("stopBtn").onclick=()=>{if(!tracking)return;tracking=false;if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;clearInterval(timer);currentTrip.end=new Date().toISOString();currentTrip.distanceM=distanceM;currentTrip.durationMs=new Date(currentTrip.end)-new Date(currentTrip.start);trips.unshift(currentTrip);save();currentTrip=null;$("startBtn").disabled=false;$("stopBtn").disabled=true;$("tripStatus").textContent="Trip saved";$("gpsStatus").textContent="Tracking stopped";renderTrips();};
function updateTripUI(){if(tracking&&currentTrip){$("distance").textContent=km(distanceM);$("elapsed").textContent=duration(Date.now()-new Date(currentTrip.start));$("pointCount").textContent=currentTrip.points.length;$("routeSummary").textContent=`${currentTrip.points.length} GPS points recorded · ${currentTrip.stops.length} matched stops`;}}
$("matchBtn").onclick=()=>{if(!currentPosition)return;let m=nearestCustomer(currentPosition);$("nearest").textContent=m?`${m.customer.name} · ${m.customer.address} · ${Math.round(m.distance)} metres away${m.customer.notes?" · Instructions: "+m.customer.notes:""}`:"No customer with saved GPS coordinates. Edit a customer and use Use my GPS at the destination."};
$("mapBtn").onclick=()=>{if(currentPosition)window.open(`https://www.google.com/maps?q=${currentPosition.latitude},${currentPosition.longitude}`,"_blank")};
function renderTrips(){$("tripList").innerHTML=trips.length?trips.map(t=>`<article class="trip-card"><h3>${new Date(t.start).toLocaleString()}</h3><p>Distance: <b>${km(t.distanceM||0)}</b> · Elapsed: <b>${duration(t.durationMs||0)}</b></p><p>${(t.points||[]).length} GPS points · ${(t.stops||[]).length} matched stops</p>${(t.stops||[]).length?`<p>Stops: ${t.stops.map(s=>esc(s.name)).join(", ")}</p>`:""}<div class="card-actions"><button class="secondary" onclick="viewTrip('${t.id}')">View route</button><button class="danger" onclick="deleteTrip('${t.id}')">Delete</button></div></article>`).join(""):'<div class="empty">No saved trips yet. Start a trip from the Dashboard.</div>'}
window.viewTrip=id=>{let t=trips.find(x=>x.id===id);if(t&&t.points&&t.points.length){let p=t.points[Math.floor(t.points.length/2)];window.open(`https://www.google.com/maps?q=${p.lat},${p.lng}`,"_blank")}else alert("This trip has no GPS points.")};
window.deleteTrip=id=>{if(confirm("Delete this trip record?")){trips=trips.filter(t=>t.id!==id);save();renderTrips()}};
function download(name,content,type="text/csv"){let blob=new Blob([content],{type:type+";charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function csvCell(v){return '"'+String(v??"").replace(/"/g,'""')+'"'}
function parseCSV(text){let rows=[],row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){let ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')quoted=false;else cell+=ch}else if(ch==='"')quoted=true;else if(ch===","){row.push(cell);cell=""}else if(ch==="\n"){row.push(cell.replace(/\r$/,""));rows.push(row);row=[];cell=""}else cell+=ch}if(cell.length||row.length){row.push(cell.replace(/\r$/,""));rows.push(row)}return rows}
$("importBtn").onclick=()=>$("csvFile").click();
$("csvFile").onchange=async e=>{let file=e.target.files[0];if(!file)return;try{let rows=parseCSV(await file.text());if(rows.length<2)throw Error("CSV has no data rows");let heads=rows.shift().map(x=>x.trim().toLowerCase());let idx=(...names)=>heads.findIndex(h=>names.includes(h));let ni=idx("name","customer","customer name"),ai=idx("address","delivery address"),pi=idx("phone"),noi=idx("notes","instructions","delivery instructions"),lati=idx("lat","latitude"),lngi=idx("lng","lon","longitude");if(ni<0||ai<0)throw Error("CSV must include Name and Address columns");let added=0;for(let r of rows){if(!r[ni]?.trim()||!r[ai]?.trim())continue;customers.push({id:crypto.randomUUID(),name:r[ni].trim(),address:r[ai].trim(),phone:pi>=0?r[pi]:"",notes:noi>=0?r[noi]:"",lat:lati>=0&&r[lati]!==""?Number(r[lati]):null,lng:lngi>=0&&r[lngi]!==""?Number(r[lngi]):null});added++}save();renderCustomers();alert(`Imported ${added} customer(s).`)}catch(err){alert("Import failed: "+err.message)}e.target.value=""};
$("exportCustomersBtn").onclick=()=>{let headers=["Name","Address","Phone","Notes","Latitude","Longitude"];download("drivetrack-customers.csv",[headers,...customers.map(c=>[c.name,c.address,c.phone,c.notes,c.lat??"",c.lng??""])].map(r=>r.map(csvCell).join(",")).join("\r\n")||headers.join(","))};
$("exportTripsBtn").onclick=()=>{let h=["Start","End","Distance km","Elapsed seconds","GPS points","Stops"];let rows=trips.map(t=>[t.start,t.end,((t.distanceM||0)/1000).toFixed(3),Math.round((t.durationMs||0)/1000),(t.points||[]).length,(t.stops||[]).map(s=>s.name).join("; ")]);download("drivetrack-trips.csv",[h,...rows].map(r=>r.map(csvCell).join(",")).join("\r\n"))};
renderCustomers();renderTrips();
if("serviceWorker" in navigator && location.protocol.startsWith("http"))navigator.serviceWorker.register("./sw.js").catch(()=>{});
