const KEY='deliveryMileageTrackerV2';let data=JSON.parse(localStorage.getItem(KEY)||'{"records":[],"activeTrip":null}');let watchId=null;
const $=id=>document.getElementById(id),save=()=>{localStorage.setItem(KEY,JSON.stringify(data));render()},now=()=>new Date().toISOString(),km=n=>Number(n||0).toFixed(1),fmtDate=s=>new Date(s).toLocaleString([], {dateStyle:'medium',timeStyle:'short'});function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){let a=!!data.activeTrip;$('startTrip').disabled=a;$('finishTrip').disabled=!a;$('startOdo').disabled=a;$('endOdo').disabled=!a;$('tripStatus').textContent=a?`Trip started ${fmtDate(data.activeTrip.startedAt)} · GPS points: ${data.activeTrip.points.length}`:'No trip running';let d=new Date();d.setHours(0,0,0,0);let w=new Date(d);w.setDate(d.getDate()-d.getDay());let t=0,ww=0,c=0;data.records.forEach(r=>{let x=new Date(r.date);if(x>=d)t+=r.km;if(x>=w)ww+=r.km;if(r.type==='delivery')c++});$('todayKm').textContent=km(t);$('weekKm').textContent=km(ww);$('deliveryCount').textContent=c;let items=[...data.records].reverse();$('history').innerHTML=items.length?items.map(r=>r.type==='trip'?`<div class="history-item"><strong>🚗 Trip — ${km(r.km)} km</strong><div class="muted">${fmtDate(r.date)} · Odometer ${km(r.startOdo)} → ${km(r.endOdo)} · GPS ${r.points.length} points</div></div>`:`<div class="history-item"><strong>📦 ${esc(r.name)}</strong><div>${esc(r.address||'No address')}</div><div class="muted">${fmtDate(r.date)} · ${km(r.km)} km${r.notes?' · '+esc(r.notes):''}</div></div>`).join(''):'<div class="muted">No records yet.</div>';renderMap()}
function renderMap(){let trips=data.records.filter(r=>r.type==='trip'&&r.points?.length);if(data.activeTrip?.points?.length)trips.push(data.activeTrip);let pts=trips.flatMap(t=>t.points||[]);if(!pts.length){$('map').innerHTML='<div class="map-placeholder">GPS route will appear here.</div>';return}let lat=pts.reduce((a,p)=>a+p.lat,0)/pts.length,lon=pts.reduce((a,p)=>a+p.lon,0)/pts.length,scale=80000,xy=p=>({x:50+(p.lon-lon)*scale,y:50-(p.lat-lat)*scale});let all=pts.map(xy),minx=Math.min(...all.map(p=>p.x)),maxx=Math.max(...all.map(p=>p.x)),miny=Math.min(...all.map(p=>p.y)),maxy=Math.max(...all.map(p=>p.y)),sx=60/(maxx-minx||1),sy=60/(maxy-miny||1),cv=p=>({x:20+(p.x-minx)*sx,y:20+(p.y-miny)*sy});let paths='',circles='';trips.forEach(t=>{let a=t.points.map(xy).map(cv);paths+=`<polyline class="route" points="${a.map(p=>p.x+','+p.y).join(' ')}"/>`;a.forEach(p=>circles+=`<circle class="point" cx="${p.x}" cy="${p.y}" r="1.8"/>`)});$('map').innerHTML=`<svg class="map-svg" viewBox="0 0 100 100" preserveAspectRatio="none">${paths}${circles}</svg>`;$('mapNote').textContent=`GPS route: ${pts.length} recorded points. Coordinates are included in exports.`}
function startGPS(){if(!navigator.geolocation){$('tripResult').textContent='GPS is not available in this browser.';return}watchId=navigator.geolocation.watchPosition(p=>{if(!data.activeTrip)return;data.activeTrip.points.push({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,time:now()});save()},()=>{$('tripResult').textContent='Trip started, but GPS permission/location is unavailable.'},{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function stopGPS(){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null}}
$('startTrip').onclick=()=>{let o=Number($('startOdo').value);if(!Number.isFinite(o)||o<0)return alert('Enter a valid starting odometer reading.');data.activeTrip={startOdo:o,startedAt:now(),points:[]};$('tripResult').textContent='Trip started. Allow location access when asked.';save();startGPS()};
$('finishTrip').onclick=()=>{let e=Number($('endOdo').value);if(!Number.isFinite(e)||e<0)return alert('Enter a valid ending odometer reading.');if(e<data.activeTrip.startOdo)return alert('Ending odometer cannot be lower than starting odometer.');data.records.push({type:'trip',date:now(),startOdo:data.activeTrip.startOdo,endOdo:e,km:e-data.activeTrip.startOdo,points:data.activeTrip.points});data.activeTrip=null;stopGPS();$('startOdo').value='';$('endOdo').value='';$('tripResult').textContent='Trip saved with GPS route.';save()};
$('addDelivery').onclick=()=>{let n=$('deliveryName').value.trim(),a=$('deliveryAddress').value.trim(),k=Number($('deliveryKm').value||0);if(!n)return alert('Enter a delivery or order number.');if(!Number.isFinite(k)||k<0)return alert('Enter a valid distance.');data.records.push({type:'delivery',date:now(),name:n,address:a,km:k,notes:$('deliveryNotes').value.trim()});$('deliveryName').value='';$('deliveryAddress').value='';$('deliveryKm').value='';$('deliveryNotes').value='';save()};
function download(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('exportJson').onclick=()=>download('delivery-mileage-backup.json',JSON.stringify(data,null,2),'application/json');
$('exportCsv').onclick=()=>{let rows=[['Type','Date','Delivery/Order','Address','Start Odometer','End Odometer','Distance Km','Notes','GPS Points']];data.records.forEach(r=>rows.push([r.type,r.date,r.name||'',r.address||'',r.startOdo??'',r.endOdo??'',r.km,r.notes||'',r.points?.length||0]));download('delivery-mileage.csv',rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv')};
function editDelivery(index){const r=data.records[index];const n=prompt('Delivery / order #',r.name||'');if(n===null)return;const a=prompt('Delivery address',r.address||'');if(a===null)return;const d=prompt('Distance (km)',r.km??0);if(d===null)return;const k=Number(d);if(!Number.isFinite(k)||k<0)return alert('Invalid distance.');const notes=prompt('Notes',r.notes||'');if(notes===null)return;r.name=n.trim();r.address=a.trim();r.km=k;r.notes=notes.trim();save()}
function deleteDelivery(index){if(confirm('Delete this delivery?')){data.records.splice(index,1);save()}}
function addDeliveryButtons(){const items=[...document.querySelectorAll('.history-item')];let ri=data.records.length-1;for(let i=0;i<items.length;i++,ri--){const r=data.records[ri];if(!r||r.type!=='delivery')continue;items[i].insertAdjacentHTML('beforeend',`<div class="delivery-actions"><button class="small edit-btn" data-edit="${ri}">Edit</button><button class="small danger" data-delete="${ri}">Delete</button></div>`)}document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editDelivery(+b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteDelivery(+b.dataset.delete))}
const originalRender=render;render=function(){originalRender();addDeliveryButtons()}
$('importBtn').onclick=()=>{const file=$('importFile').files[0];if(!file)return alert('Choose a CSV file first.');const reader=new FileReader();reader.onload=()=>{const lines=String(reader.result).split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return alert('The CSV has no delivery rows.');const parse=line=>{let out=[],cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out};const h=parse(lines[0]).map(x=>x.trim().toLowerCase());const find=(...ns)=>{for(const n of ns){const i=h.indexOf(n);if(i>=0)return i}return -1};const ni=find('delivery/order','delivery / order','name','delivery'),ai=find('address','delivery address'),ki=find('distance km','distance','km'),oi=find('notes','note');if(ni<0)return alert('Could not find a Delivery/Order column.');let count=0;for(const line of lines.slice(1)){const c=parse(line),name=(c[ni]||'').trim(),k=Number((c[ki]||'0').trim());if(!name||!Number.isFinite(k)||k<0)continue;data.records.push({type:'delivery',date:now(),name,address:ai>=0?(c[ai]||''):'',km:k,notes:oi>=0?(c[oi]||''):''});count++}save();$('importResult').textContent=`Imported ${count} delivery${count===1?'':'ies'}.`};reader.readAsText(file)};
$('clearAll').onclick=()=>{if(confirm('Delete all saved records?')){stopGPS();data={records:[],activeTrip:null};save()}};render();